name: "test and linters"
on:
  workflow_call:

    inputs:
      BRANCH_NAME:
        description: 'name of branch main/master'
        required: false
        type: string
        default: "main"



env:
  branch_flag: ${{ github.event_name == 'push' && github.ref == 'refs/heads/${{ inputs.BRANCH_NAME }}' }}
  ref: ${{ github.ref }}
jobs:
  build:
    runs-on: ubuntu-latest
    name: ðŸ§ª Test and ðŸ”¨ Build

    steps:
      - name: debug
        run: |
          echo ${{ env.branch_flag }} 

      - if: ${{ env.branch_flag }}
        name: test45
        run: echo "should run"